"""Render references/pairs.json into references/pairs.md (human-readable twin).

    python skills/judge-score-risk/scripts/pairs_to_md.py           # rewrite pairs.md
    python skills/judge-score-risk/scripts/pairs_to_md.py --check  # exit 1 when stale

pairs.md carries one ### section per pair with a prints: line, which the
distill gate counts as a tested pair.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAIRS = HERE.parent / "references" / "pairs.json"
MD = HERE.parent / "references" / "pairs.md"

GROUPS = {"score": "Score every verdict in YAML", "risk": "Flag untrusted input and name the risk", "dedupe": "Key the verdict by fingerprint", "scope": "Cap the context to added lines", "report": "File the scored report"}


def render(doc: dict) -> str:
    lines = [
        "# Tested pairs: vague verdicts and the scored-verdict fix",
        "",
        "Made from pairs.json. Do not edit this file by hand.",
        "Every pair ran in pwsh 7 in its own scratch copy of the fixture. `bad` reads a guessed review-packet path that was never committed and throws the Cannot find path line. `good` reads only the capped packet files and prints the answer shown.",
        "",
    ]
    by_group: dict[str, list[dict]] = {}
    for p in doc["pairs"]:
        by_group.setdefault(p.get("group", "dispatch"), []).append(p)
    for group, pairs in by_group.items():
        lines += [f"## {GROUPS.get(group, group)}", ""]
        for p in pairs:
            lines.append(f"### {p['id']}")
            if p.get("bad") is not None:
                lines += [f"bad (throws: {p.get('bad_error', 'see pairs.json')}):", "```", f"{p['bad']}", "```"]
            if p.get("good") is not None:
                lines += ["good:", "```", f"{p['good']}", "```"]
                lines.append(f"prints: `{p.get('expect', p.get('expect_regex', ''))}`")
            lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    doc = json.loads(PAIRS.read_text(encoding="utf-8"))
    want = render(doc)
    if "--check" in argv:
        if not MD.is_file() or MD.read_text(encoding="utf-8").replace("\r\n", "\n") != want.replace("\r\n", "\n"):
            print("pairs.md is stale: run python skills/judge-score-risk/scripts/pairs_to_md.py")
            return 1
        print("pairs.md is current")
        return 0
    MD.write_text(want, encoding="utf-8", newline="\n")
    print(f"wrote {MD} ({len(doc['pairs'])} pairs)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
