"""Write references/pairs.md from references/pairs.json (the one source of truth).

    python skills/pwsh-for-bash-writers/scripts/pairs_to_md.py          # rewrite pairs.md
    python skills/pwsh-for-bash-writers/scripts/pairs_to_md.py --check  # exit 1 when pairs.md is stale
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REFS = Path(__file__).resolve().parent.parent / "references"

TITLES = {
    "search": "Search text",
    "slice": "Cut and count text",
    "files": "Files and folders",
    "time": "Time",
    "shell": "Shell habits",
    "quoting": "Quotes and strings",
    "paths": "Paths",
    "exit": "Exit codes",
}


def render(doc: dict) -> str:
    out = [
        "# Tested pairs: bash habit and the pwsh form",
        "",
        "Made from pairs.json. Do not edit this file by hand.",
        "Every pair ran in pwsh 7 with Git's usr/bin off PATH. `bad` failed or gave a wrong answer. `good` printed the answer shown.",
        "",
    ]
    groups: dict[str, list[dict]] = {}
    for p in doc["pairs"]:
        groups.setdefault(p["group"], []).append(p)
    for key, title in TITLES.items():
        if key not in groups:
            continue
        out += [f"## {title}", ""]
        for p in groups[key]:
            out.append(f"### {p['id']}")
            if p.get("bad") is not None:
                kind = "gives a wrong answer without an error" if p.get("bad_silent") else f"fails: {p['bad_error']}"
                out += [f"bad ({kind}):", "```", p["bad"], "```"]
            out += ["good:", "```", p["good"], "```"]
            if p.get("expect"):
                out.append(f"prints: `{p['expect']}`")
            if p.get("note"):
                out.append(p["note"])
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    doc = json.loads((REFS / "pairs.json").read_text(encoding="utf-8"))
    text = render(doc)
    target = REFS / "pairs.md"
    if "--check" in argv:
        stale = not target.exists() or target.read_text(encoding="utf-8") != text
        print("pairs.md is stale: run pairs_to_md.py" if stale else "pairs.md is current")
        return 1 if stale else 0
    target.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {target} ({len(text)} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
