"""Render references/pairs.json into references/pairs.md (human-readable twin).

    python skills/idiomatic-rust/scripts/pairs_to_md.py
    python skills/idiomatic-rust/scripts/pairs_to_md.py --check

pairs.md carries one ### section per pair with a prints line, which the
distill gate counts as a tested pair.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAIRS = HERE.parent / "references" / "pairs.json"
MD = HERE.parent / "references" / "pairs.md"

GROUPS = {"naming": "Names and flow", "flow": "Names and flow", "build": "Building blocks", "borrow": "Borrowing and avoidance"}


def render(doc: dict) -> str:
    lines = [
        "# Tested pairs: the Rustacean misses and the idiomatic fixes",
        "",
        "Made from pairs.json. Do not edit this file by hand.",
        "Every pair runs through scripts/idiomatic_rust.py. bad replays the miss. good prints the answer shown.",
        "",
    ]
    by_group: dict[str, list[dict]] = {}
    for p in doc["pairs"]:
        by_group.setdefault(p.get("group", "naming"), []).append(p)
    for group, pairs in by_group.items():
        lines += ["## " + GROUPS.get(group, group), ""]
        for p in pairs:
            lines.append("### " + p["id"])
            lines.append("")
            lines.append(p.get("title", ""))
            lines.append("")
            lines.append("bad:")
            lines.append("```rust")
            lines.append(p.get("bad_code", ""))
            lines.append("```")
            lines.append("good:")
            lines.append("```rust")
            lines.append(p.get("good_code", ""))
            lines.append("```")
            lines.append("prints: `" + p.get("expect", "") + "`")
            lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    doc = json.loads(PAIRS.read_text(encoding="utf-8"))
    want = render(doc)
    if "--check" in argv:
        if not MD.is_file() or MD.read_text(encoding="utf-8").replace("\r\n", "\n") != want.replace("\r\n", "\n"):
            print("pairs.md is stale: run python skills/idiomatic-rust/scripts/pairs_to_md.py")
            return 1
        print("pairs.md is current")
        return 0
    MD.write_text(want, encoding="utf-8", newline="\n")
    print("wrote " + str(MD) + " (" + str(len(doc["pairs"])) + " pairs)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))

