"""Render references/pairs.json into references/pairs.md (human-readable twin).

    python skills/lsd-ls/scripts/pairs_to_md.py           # rewrite pairs.md
    python skills/lsd-ls/scripts/pairs_to_md.py --check  # exit 1 when stale

pairs.md carries one ### section per pair with a prints: line, which the
distill gate counts as a tested pair.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAIRS = HERE.parent / "references" / "pairs.json"
MD = HERE.parent / "references" / "pairs.md"

GROUPS = {"listing": "Aliases, icons, git and tables", "display": "Trees, sorts, config and isolation",
          "pin": "Pin replays"}


def render(doc: dict) -> str:
    lines = [
        "# Tested pairs: the lsd-ls directory-listing misses and the fixed queries",
        "",
        "Made from pairs.json. Do not edit this file by hand.",
        "Every pair ran in pwsh 7 in its own scratch copy of the fixture. `bad` replays the miss. `good` prints the answer shown.",
        "",
    ]
    by_group: dict[str, list[dict]] = {}
    for p in doc["pairs"]:
        by_group.setdefault(p.get("group", "listing"), []).append(p)
    for group, pairs in by_group.items():
        lines += [f"## {GROUPS.get(group, group)}", ""]
        for p in pairs:
            lines.append(f"### {p['id']}")
            if p.get("bad") is not None:
                lines += [f"bad (throws: {p.get('bad_error', 'see pairs.json')}:", "```", f"{p['bad']}", "```"]
            if p.get("good") is not None:
                lines += ["good:", "```", f"{p['good']}", "```"]
                lines.append(f"prints: `{p.get('expect', p.get('expect_regex', ''))}`")
            lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    doc = json.loads(PAIRS.read_text(encoding="utf-8"))
    want = render(doc)
    if "--check" in argv:
        if not MD.is_file() or MD.read_text(encoding="utf-8").replace("\r\n", "\n") != want.replace("\r\n", "\n"):
            print("pairs.md is stale: run python skills/lsd-ls/scripts/pairs_to_md.py")
            return 1
        print("pairs.md is current")
        return 0
    MD.write_text(want, encoding="utf-8", newline="\n")
    print(f"wrote {MD} ({len(doc['pairs'])} pairs)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
