"""Render references/pairs.json into references/pairs.md (human-readable twin).

    python skills/handsrust-code/scripts/pairs_to_md.py           # rewrite pairs.md
    python skills/handsrust-code/scripts/pairs_to_md.py --check  # exit 1 when stale

pairs.md carries one ### section per pair, which the skill's test counts as
a tested pair next to the SKILL.md [src:] anchors.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAIRS = HERE.parent / "references" / "pairs.json"
MD = HERE.parent / "references" / "pairs.md"

GROUPS = {"state": "Flappy states", "dungeon": "Seeded dungeons",
          "ecs": "Intent and collisions"}


def step_lines(step: dict) -> list[str]:
    out = []
    if "write" in step:
        out.append(f"write {', '.join(sorted(step['write']))}")
    if "argv" in step:
        where = f" in {step['cwd']}" if step.get("cwd", ".") != "." else ""
        cmd = " ".join(step["argv"])
        if not cmd.startswith("cargo "):
            cmd = f"cargo {cmd}"
        out.append(f"run `{cmd}`{where} (exit {step.get('expect_exit', 0)})")
        out.extend(f"shows `{f}`" for f in step.get("expect", []))
        out.extend(f"hides `{f}`" for f in step.get("absent", []))
        if "count" in step:
            out.append(f"counts `{step['count']['fragment']}` x{step['count']['times']}")
    for rel in step.get("assert_exists", []):
        out.append(f"file present: `{rel}`")
    for rel in step.get("assert_absent", []):
        out.append(f"file absent: `{rel}`")
    if "assert_contains" in step:
        spec = step["assert_contains"]
        out.append(f"`{spec['file']}` holds {', '.join(f'`{f}`' for f in spec.get('fragments', []))}")
    return out


def render(doc: dict) -> str:
    lines = [
        "# Tested pairs: the handsrust-code rules, each replayed with real cargo",
        "",
        "Made from pairs.json. Do not edit this file by hand.",
        "Every pair runs with real cargo 1.97.1 in its own fresh scratch directory under $TEMP/opencode with no network (see scripts/handsrust_code.py). `good` prints the output shown; `bad` fails with the real error named.",
        "",
    ]
    by_group: dict[str, list[dict]] = {}
    for p in doc["pairs"]:
        by_group.setdefault(p.get("group", "state"), []).append(p)
    for group, pairs in by_group.items():
        lines += [f"## {GROUPS.get(group, group)}", ""]
        for p in pairs:
            lines.append(f"### {p['id']}")
            lines.append(p.get("title", ""))
            lines.append("")
            for side in ("bad", "good"):
                spec = p.get(side)
                if spec is None:
                    continue
                lines.append(f"{side}:")
                for step in spec.get("steps", []):
                    for text in step_lines(step):
                        lines.append(f"- {text}")
            lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    doc = json.loads(PAIRS.read_text(encoding="utf-8"))
    want = render(doc)
    if "--check" in argv:
        if not MD.is_file() or MD.read_text(encoding="utf-8").replace("\r\n", "\n") != want.replace("\r\n", "\n"):
            print("pairs.md is stale: run python skills/handsrust-code/scripts/pairs_to_md.py")
            return 1
        print(f"pairs.md is current ({len(doc['pairs'])} pairs)")
        return 0
    MD.write_text(want, encoding="utf-8", newline="\n")
    print(f"wrote {MD} ({len(doc['pairs'])} pairs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
